### ISSUE TITLE
fio-histo-log-pctiles.py command not found

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#1001]
I can get pbench-fio to produce the output file but it errs attempting to do the histogram data. The hist.csv file was empty.

/opt/pbench-agent/bench-scripts/pbench-fio: line 632: fio-histo-log-pctiles.py: command not found
ERROR: hit end of file without seeing header
/opt/pbench-agent/bench-scripts/pbench-fio: line 640: fio-histo-log-pctiles.py: command not found
ERROR: hit end of file without seeing header

  pbench-agent-0.54-1g4802e4ba.noarch
  pbench-agent-internal-0.54-1.noarch
  pbench-fio-3.12-1.x86_64

http://death.perf.lab.eng.bos.redhat.com/pub/perfshift02/181203-0931_pbfio-randwrite-1i-4Kbs-4iod-10m_test07/

**Comment by ndokos** [comment]
The fio Makefile does not install this script.

I added a patch so that the Makefile installs `fio-histo-log-pctiles.py` and remade the pbench-fio RPM, Please run

     yum update pbench-fio

and make sure that you get the pbench-fio.3.12.2 version.

Ultimately, this will have to be fixed upstream, so I'll open an issue, if there is not one already.

**Comment by ndokos** [comment]
The F29 RPM remains TBD.

**Comment by ndokos** [comment]
See https://github.com/axboe/fio/issues/701

**Comment by ndokos** [comment]
The F29 RPM has been remade.

**Comment by portante** [comment]
Looks like the fix to this was to move to `fio` v3.12, with an updated version built with the change.
