### ISSUE TITLE
Summary page does not load after selecting a search result

### ISSUE THREAD

**Issue by ashishkamra** [distributed-system-analysis/pbench#1032]
Workflow:
1. Browsed to the search view - "http://pbench.perf.lab.eng.bos.redhat.com/dashboard/#/search"
2. Selected "2018-12" as the index instead of the default.
3. Clicked on search.
4. Selected the following run
![image](https://user-images.githubusercontent.com/10819719/51399634-676cf300-1b14-11e9-8f4e-82321759e84d.png)
5. The summary page is blank.
6. No way to get back to the search page other than refreshing the URL

**Comment by gurbirkalsi** [comment]
@portante Is this related to the indexing issues we are having? I was not able to find that run in the results directory under production.

**Comment by gurbirkalsi** [comment]
@ashishkamra You should be able to get back to the search page if you go back a page or click on the search icon on the lefthand navigation menu. Which browser were you using to test this?

**Comment by ashishkamra** [comment]
The empty summary page has the URL - http://pbench.perf.lab.eng.bos.redhat.com/dashboard/#/dashboard/summary. Clicking on the back button takes me to http://pbench.perf.lab.eng.bos.redhat.com/dashboard/#/search but does not reload the page. I have to manually reload it to get the search page back. I am using chrome Version 65.0.3325.181 (Official Build) (64-bit).

**Comment by portante** [comment]
This is an example of a pbench run that was uploaded using a prefix.  In the metadata, the "`prefix`" variable holds the value, "`create_500PVC`", which means the results URL is http://pbench.perf.lab.eng.bos.redhat.com/results/b06-h31-1029p/create_500PVC/pbench-user-benchmark_createvols_500_2018.12.05T13.03.48/.

However, if you used "`incoming`" instead of "`results`" you'd the tar ball directory without the prefix.  The prefix is what the user is expecting to see with the results URL.

So in the future, for accessing data for UI needs, use the incoming URL.  When you need to generate a URL for the user to use, you'll want to construct the results URL using the prefix value.

**Comment by gurbirkalsi** [comment]
@portante Is there another way I can grab this prefix definition without having to make a query to the `metadata.log` file? Perhaps indexing as part of a run document within elasticsearch?

**Comment by portante** [comment]
When you fetch the "`run`" document for a result, if it has a "`run.prefix`" field then you can construct the results URL via:  `results_url + '/results/' + controller + '/' + run.prefix + '/' + result_name` (slashes fixed up as needed).

Note that not matter if a prefix is present or not, you can always get to the "incoming" directory using:  `results_url + '/incoming/' + controller + '/' + result_name` (slashes fixed up as needed).

**Comment by gurbirkalsi** [comment]
I've filed a resolution for this issue at #1037

**Comment by portante** [comment]
Fixed by #1037.
