### ISSUE TITLE
network error from PDash on pbench-fio test result

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#1034]
I selected one of Elko's pbench test datasets , search for "b06-h31" and you'll find it, here's a screenshot
![screenshot from 2019-01-21 12-55-24](https://user-images.githubusercontent.com/1717107/51491331-0b0c0c80-1d7c-11e9-98d1-a1906f6b3f92.png)

And when I press the "Compare Results" button, I get a message box with title "network error", followed by:

"The selected iteration's resources are too large to parse in the browser. Please try another result."

I couldn't get the screenshot because the message box goes away.   I'm not sure why I'm getting this error.  Is it the wrong pbench version?  Is it that there isn't a clear specification for what is to be compared?  Or is it really just too much data?

**Comment by gurbirkalsi** [comment]
@bengland2 Hi Ben, I tried searching for that result you selected under `/results` on production and wasn't able to find the result indexed under production - it was only indexed with elasticsearch. Since we don't index result.json file data in elasticsearch, we query them from the production server in order to build the comparison. 

I should update the error message to reflect that the result.json file was not found as a result of the 404.

**Comment by gurbirkalsi** [comment]
@bengland2 Please disregard the last comment. This is an issue where the dashboard is not using the the prefix value for constructing the url to query against the production server. 

I'll be filing a PR shortly to resolve this issue so that we can fetch result.json data using the correct constructed url to production. For more details, please see the following discussion: https://github.com/distributed-system-analysis/pbench/issues/1034

**Comment by gurbirkalsi** [comment]
I've filed a resolution for this issue at #1037

**Comment by portante** [comment]
The fix from #1037 addresses the issue with pbench results have a "prefix" specified.  But once that issue is solved, the next issue brought up here is that the `result.json` files are too big to load into the browser.

We need to fix the server-side indexing to provide JSON documents in Elasticsearch that the dashboard can query without the need to ingest large JSON documents to find it.

**Comment by gurbirkalsi** [comment]
Parsed Iteration JSON: https://gist.github.com/gurbirkalsi/23ab49de69666b4224625044eaa3e692

**Comment by gurbirkalsi** [comment]
Parsed Column JSON: https://gist.github.com/gurbirkalsi/2d538d90424f87dcfe69e600ee3ed1bd

**Comment by portante** [comment]
Seems to be fixed by #1073.
