### ISSUE TITLE
Iteration filters do not appear to actually work on comparison page

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1158]
It does not appear that the iteration filters are working on the comparison page.

If I select "`8`" for the "instances" filter below:

![PbenchIterationFilterNotWorkingBefore-20190402](https://user-images.githubusercontent.com/949097/55424063-64977100-554d-11e9-8ef4-092569b07a1a.png)

Then issue the comparison page, I see both instances with `8` and with `1`:

![PbenchIterationFilterNotWorkingAfter-20190402](https://user-images.githubusercontent.com/949097/55424151-a0cad180-554d-11e9-822f-05fde42ccccd.png)

Controller perf138, results "`uperf_uperf_rhel8_4.18.0-78_rc2.el8_intel_40gb_2019.03.12T00.58.27`" and "`uperf_uperf_rhel77_3.10.0-1030.el7_intel_40gb_switch_2019.03.23T03.08.02`".

**Comment by gurbirkalsi** [comment]
@portante the iteration filters appear to be filtering the instances properly on my build of the dashboard; however, the reason you are seeing this behavior is because you've selected the `Compare All Iterations` button which ignores the filters selected and launches a comparison using all of the iterations. I'm going to improve the UX here by showing the user which iterations are selected by default and only use one comparison launch button to avoid confusion.

**Comment by gurbirkalsi** [comment]
@portante This issue has been resolved with the merge of PR #1165
