### ISSUE TITLE
Error checking in the shim scripts

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1191]
`pbench-server-prep-shim-002` loops over md5 files in its reception area: it will not look for anything else, so if something else ends up in the reception area (e.g. a partially copied tarball without an md5 file, or an md5.check file that never got promoted to an md5 file), it will stay there forever. Somebody needs to check and clean these remnants out.

**Comment by ndokos** [comment]
Probably the first step to deal with such files is to enhance the server audit script to detect those files and report them, so at least we are made aware of them.

**Comment by portante** [comment]
We talked through this situation and because there is not atomicity in how the agent copies data to the server, or with how the shim copies data to the archive area from the reception area, the audit server cannot validate the states here.

The only thing we could do is consider implementing https://github.com/distributed-system-analysis/pbench/issues/1024, which would allow us to implement the tar ball ingestion atomically.
