### ISSUE TITLE
warning: timestamp already exists with this RW type

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#1228]
When I run the following pbench-fio command on RHEL8 GA server, I get "warning: timestamp already exists with this RW type, skipping this sample" errors such as this one, what does this mean?   Does it mean fio won't postprocess my results to get averages, etc?
```
running fio job: /var/lib/pbench-agent/fio___iodepth-12_size-1250G_ioengine-libaio__baremetal_4.18.0-80.el8.x86_64__norandommap_2019.06.07T15.03.26/1-write-4KiB/sample3/fio.job
fio job complete
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio___iodepth-12_size-1250G_ioengine-libaio__baremetal_4.18.0-80.el8.x86_64__norandommap_2019.06.07T15.03.26/1-write-4KiB/sample3/clients/localhost/fio_clat.1.log timestamp = 20000, value = 42727, rwtype = 1)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio___iodepth-12_size-1250G_ioengine-libaio__baremetal_4.18.0-80.el8.x86_64__norandommap_2019.06.07T15.03.26/1-write-4KiB/sample3/clients/localhost/fio_lat.1.log timestamp = 20000, value = 44727, rwtype = 1)
```
Here is my fio command:
```
/opt/pbench-agent/bench-scripts/pbench-fio --sysinfo=none \
  --config=__iodepth-1_size-1250G_ioengine-libaio__baremetal_4.18.0-80.el8.x86_64__norandommap \
 --test-types=write --ramptime=5 --direct=1 --runtime=20 --block-sizes=4 \
 --targets=/dev/crypt-test/unencrypted_lv --samples=3 \
 --ioengine=libaio --file-size=1250G --numjobs=1 --iodepth=1
```
Here are pbench versions:
```
[root@e24-h09-740xd dmcrypt]# rpm -qa | grep pbench
pbench-agent-0.60-1gc9e89f8f.noarch
pbench-sysstat-12.0.3-1.x86_64
pbench-agent-internal-0.60-1.noarch
pbench-fio-3.12-1.x86_64
```

**Comment by atheurer** [comment]
It will still generate an average and all the normal stats.  The problem is that fio is producing two stats for the exact same timestamp in the exact same job, which IMO is not possible.  So, we use the first occurrence of that stat and ignore any other values with the same timestamp.  If that is incorrect, then please let us know what we should be doing with them, or explain why fio is doing this.  If we need to process all of them, then the only alternative I can think of is averaging the multiple values (for the same timestamp) into 1 value and use that.  However, before we do that, I would like to understand why fio does this in the first place.
