### ISSUE TITLE
pbench on rhev hypervisor

### ISSUE THREAD

**Issue by psuriset** [distributed-system-analysis/pbench#124]
Supporting pbench tools to install  on rhev hypervisor  to run benchmarks

**Comment by portante** [comment]
For now I'm adding the "won't fix" label because we'd have to get RHEV to install the necessary bits on the hypervisor, and that is for a very small niche in the grand space of our use cases.

Best to record it here so that when folks go looking we'll have this issue to hang future discussions off of.
