### ISSUE TITLE
Containerize tools (start/stop)

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1245]
We need to change the way we handle tools to leverage containers.  The primary reason is to make tools more supportable by reducing the software stack for the tools to one embodied in the container image.

The secondary reason is to reduce the interface "surface" of running tools to something more managable (ssh to start, to start, scp to collect data, etc. had many points of failure that add instability).

The tertiary reason is to make the pbench method of running tools and collecting their data available as a supported interface of pbench (today, `pbench-start`/`stop-tools` is not really supported well; people use them, but can't take advantage of anything offered by the rest of pbench (indexing that data on the server side, for example)).

The approach being considered is simple:
 * use a container to embody the environment for a given tool (all necessary software dependencies)
 * provide a mechanism to send a message to tell that tool to start running
 * provide a mechanism to send a message to tell that tool to stop running
 * provide a facility for that container to push collected data to an "object" repository

A tool orchestrator (today that is `pbench-start`/`stop-tools`, but this work will enable others to be created external to pbench) will be responsible for what the pbench orchestrator does:

 1. Get the tool container image onto a target host
 1. Start a tool container running from the tool container image
 1. Gracefully stop a tool container that is running
 1. Provide a fail-safe mechanism to `kill` the container should it become unresponsive

Note that a container environment like Kubernetes already provides the facilities and interfaces to support the above.

The big change we need to make is to use a message sent to the tool to start and stop runs, and a facility to have that tool send data it collects remotely instead of having it collected via `scp`.

----

Notes and related work:

 * PR #1248 introduces the notion of a "Tool Meister" which provides the facilities and interfaces necessary to start & stop tools without the need to use `ssh`/`scp` to do so
    * A pub/sub API via Redis is introduced, along with a new "Tool Data Sink" to collect data via HTTP PUT
 * PR #1317 which introduced an interface change to support multiple hosts when registering tools now that tool registration in PR #1248 is all local; see #1285
 * PRs #1441 & #1692 are a pair of substantial infrastructure changes to make it easier to work with the code base during this major refactoring
 * PRs #1460 & #1538 ("Refactor tool-scripts to use one script") are a foundational change to the way we implement tools so that they are independent of the rest of pbench, allowing for the process of containerization in the future (the bench-scripts notions of iteration and sample are removed from code implementing tools).

**Comment by k-rister** [comment]
Can you expand on the "many points of failure" you reference in the second secondary reason?  I think understanding the details of such vague statements is necessary to properly addressing the issue in whatever the upcoming solution is.

**Comment by ashishkamra** [comment]
How will "get the tool container image on to a target host" work in a non-kubernetes environment ?

**Comment by atheurer** [comment]
> How will "get the tool container image on to a target host" work in a non-kubernetes environment ?

My guess would be to support two ways:
1) As it does today, via scp/ssh.  This means the target host does not need to have a connection to a container repo, just a connection to the pbench-agent.  Since this is a "regular" linux host with persistent storage (in most cases), there could exist a cache of this image [versioned] and could be re-used instead of copying every time.
2) If the target does have access to a container repo, and it has the container utilities to pull that image from a repo, then the pbench-agent (via ssh) tells it to pull that image itself.

For execution of the container, two methods could be supported:
1) If there is no support at all to run a container, and it is not possible to install container utililties, then the container image is manually installed (tar/cpio/whatever) somewhere on the target's local FS, /proc and /sysfs are bind mounted to that same area if necessary, then chroot is used to execute.
2) If the container can be installed or are already present, then just use them to bring up the instance of that container and execute it.

**Comment by portante** [comment]
@k-rister, today we have to invoke `ssh` and `scp` multiple times to get tools running.  By reducing the number of times we need to use them we reduce all the points errors can occur.  We have very little error checking for all of those `ssh` and `scp` commands, and they are littered across the code.  Reducing them will be a big win.
