### ISSUE TITLE
Running specific benchmark without registering tools

### ISSUE THREAD

**Issue by psuriset** [distributed-system-analysis/pbench#125]
Presently pbench expects user to register tools.  Once debugging is done, user might want to run just benchmark without registering tools. 

Ex: Just run pbench_fio without registering tools.

**Comment by portante** [comment]
We might want to consider emitting a warning so that users know that the pbench run was performed without and tool data collected.

Some other questions to consider:
 * Would we still want to collect system information?
 ** I would think so, but we might want to offer a suppression option for that
 * Would we still want to track summary and result data?
 ** I would think so, but as above ...

**Comment by psuriset** [comment]
i feel, we should have remaining all stuff,  except tools  not being registered.

**Comment by ashishkamra** [comment]
@psuriset too much testing required for this change. Do we really want it?
