### ISSUE TITLE
pbench-add-metalog-option blows up when the option is a '%'

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#1329]
```
pbench-run-benchmark trafficgen <other options> --rate-unit=%
...
Traceback (most recent call last):
  File "/opt/pbench-agent/util-scripts/pbench-add-metalog-option", line 32, in <module>
    status = main(lfile, section, option)
  File "/opt/pbench-agent/util-scripts/pbench-add-metalog-option", line 22, in main
    config.set(section, option, ', '.join(sin.split()))
  File "/usr/lib64/python3.6/configparser.py", line 1193, in set
    super().set(section, option, value)
  File "/usr/lib64/python3.6/configparser.py", line 894, in set
    value)
  File "/usr/lib64/python3.6/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '%' at position 0
```

The `%` is a valid value for trafficgen's --rate-unit parameter.

**Comment by k-rister** [comment]
Should work be done to escape special characters when they are added to the metalog?  It seems like we would want the content to be logged exactly as is without any potential modification, or am I missing something?

**Comment by riya-17** [comment]
@k-rister @ndokos @portante 

As I looked into the problem the problem is in configparser Interpolation https://docs.python.org/3/library/configparser.html#configparser.InterpolationError

Configparser Interpolation does not accept '%' symbol and throws error due to that. So when we write a value with '%', ex: "30%" in any config file this error in thrown

In file /usr/lib64/python3.7/configparser.py line 400 is raising the error
```
   400	    #if '%' in tmp_value:
   401	        #    raise ValueError("invalid interpolation syntax in %r at "
   402	        #                     "position %d" % (value, tmp_value.find('%')))
```
if I comment them out they are not showing the same error again and the data is also saved as it is without any change.

**Comment by riya-17** [comment]
@portante @ndokos @k-rister Please Take a look

**Comment by ndokos** [comment]
The thing to do I think is to modify pbench-add-metalog-option to scan any input and double the % chars before entering them into the `metadata.log` file. When the value is retrieved (through either `getconf.py` or the Python ConfigParser API), the doubled % sign is unescaped properly.
