### ISSUE TITLE
Replace log_init/log_finish with use of the "logger" command

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1421]
Let's remove the `log_init` / `log_finish` methods and replace with the use of the `logger` command.

**Comment by ndokos** [comment]
I'm not really sure what we need to do here: the `logger` command always writes to `/dev/log` and we cannot modify what `/dev/log` is unless we run as root (which is going to create problems for unittests). So basically, all we can do is assume that the `/dev/log` consumer (presumably rsyslogd) is set up once and for all the way we want to.

We can then modify all the bash scripts so that error messages (output redirected to fd 4) are logged with a level of `err` and other messages (output redirected to fd 1) are logged as `info` log messages. But the destination of these messages will not be up to pbench (we cannot use `log_init/log_finish` to modify the destination, since we will not be running as root).

Is my understanding correct? Is that what you meant to do  with this issue?

**Comment by portante** [comment]
> I'm not really sure what we need to do here: the `logger` command always writes to `/dev/log` and we cannot modify what `/dev/log` is unless we run as root (which is going to create problems for unittests). So basically, all we can do is assume that the `/dev/log` consumer (presumably rsyslogd) is set up once and for all the way we want to.

On Fedora, CentOS, and RHEL boxes, /dev/log is setup to be read by journald, then rsyslog reads from the journal (if rsyslog is installed).

> 
> We can then modify all the bash scripts so that error messages (output redirected to fd 4) are logged with a level of `err` and other messages (output redirected to fd 1) are logged as `info` log messages. But the destination of these messages will not be up to pbench (we cannot use `log_init/log_finish` to modify the destination, since we will not be running as root).

Could we do something similar to the agent side with `log_warn`, `log_err` functions which use logger under the covers normally, and write to a file during unit tests?
