### ISSUE TITLE
The "perf" tool was dropped from the default tool set, should it be restored?

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1526]
As of 5d6213a, "Support for multiple hosts to pbench-register-tool" (in release [v0.66](https://github.com/distributed-system-analysis/pbench/releases/tag/v0.66) and [v0.67](https://github.com/distributed-system-analysis/pbench/releases/tag/v0.67)) the `perf` tool was dropped from the default toolset.

The default tool set in the `pbench-agent-default.cfg` file has *never* included the `perf` tool, but prior to 5d6213a `pbench-register-tool-set` always added the `perf` tool after all the other tools were registered.

A mistake was made in 5d6213a where the `perf` tool was added to the unit tests `.cfg` files but **NOT** to the `pbench-agent-default.cfg` file.

Should we add the `perf` tool to the `pbench-agent-default.cfg` file or should we leave out of the default since it has been out of there for two releases?

**Comment by mnmehta** [comment]
The default set of 7 tools in already quite rich, so I'm fine with things the way they are, and feel that anyone that wants perf can always register the tool explicitly. The fact that no one has complained about perf missing in the default toolset for 2 releases may also support keeping it out of default for now?

**Comment by portante** [comment]
PR #1527 was filed hedging the popular vote would be to restore the `perf` tool as the default.

However, if we decide we want to keep `perf` out of the default tool set, then we can modify #1527 to just verify the default tool set doesn't change in the future.

**Comment by portante** [comment]
Still waiting for more feedback.  If we don't get any by the end-of-the-day Friday, March 6th, then we'll keep the `perf` tool out of the default set, and I'll amend this commit to reflect that decision.

**Comment by k-rister** [comment]
I'm on the fence.  On one hand I think that profiler data collection is one of the most important aspects of a tool like pbench and anything that makes it easier is positive.  On the other hand we are increasingly investigating workloads (NFV, RT) where tools such as perf always running could be highly problematic (causing the exact type of behavior that we are working to avoid, ie. interruptions on a CPU core).

That said, I'm not sure if any conclusions should be reached just because nobody has complained.  I tend to run test environments for prolonged periods of time and they morph from one work item to the next without being scrubbed and restarted from scratch.  So I tend to do fresh installs of pbench on clean systems rarely, which as near as I can tell means I would not have been subjected to this new behavior (I don't usually re-run `pbench-register-tool-set` and things keep working as they before) and therefor wouldn't have know this had happened.

**Comment by portante** [comment]
@k-rister, good points.  But we need something to help us decide one-way or the other.

If we leave it as it is, in time more people will be affected, but at least by then we will have documented the change as of the 0.68 release.  That would give them a chance to adjust.

If we restore it, then at a much later time, those who started using 0.66 and 0.67 will then have `perf` data collected again, potentially impacting their workloads.

We need a way to weight the argument in favor of one direction over the other.

**Comment by k-rister** [comment]
In light of any other information then I would say restore the original behavior.

**Comment by jeniferh** [comment]
I'd say not including perf by default is probably best in terms of keeping overhead low for default measurements. It is easy enough to add perf separately, it is probably more annoying to remove perf if it is part of the default set in situations where you have many instances and don't want it everywhere.

**Comment by jeniferh** [comment]
Although I do see the argument for restoring orig behavior considering all the existing baselines previously collected..

**Comment by ndokos** [comment]
When we first learned of this, my knee-jerk reaction was "put it back", but the sensitive workloads argument has me leaning in the other direction now. @portante pointed out that we do have the ability to provide different tool sets for different needs, so I think we should leave perf (and maybe others: pidstat? proc-interrupts?) out of the default tool set, but provide additional tool sets for different needs: none, light, default, heavy perhaps. And prominently document how to choose one and also how to check what the current sets are and what they contain.

**Comment by portante** [comment]
Let's add it back.  No reason given to keep it out of the default set of sufficient way.
