### ISSUE TITLE
Most tools check for the underlying package on registration, but some do not.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1550]
The following tools are not checked currently in `base-tool`:

- `blktrace` (see issue #1548 for some comments)
- `numastat` (provided by `numactl`)
- `strace`
- `tcpdump`
- `virsh-migrate` (needs `virsh` which is provided by `libvirt-client`)
- `jmap`  (provided by `java-latest-openjdk-devel`)
- `jstack` (provided by `java-latest-openjdk-devel`)

The packages for these tools have the same name as the tool, except as noted, and the packages have the same name on RHEL 7, RHEL 8, and F31.

In addition, there are some tools whose provenance is unknown to me and not so easy to find out:

- `rabbit` (needs `rabbitmqadmin` but I cannot find who provides that)
- `qemu-migrate` (requires `nc` which is provided by `nmap-ncat` but maybe other things too)

It would be great if someone in the know could fill out that information for each of these.

**Comment by portante** [comment]
Note that each tool datalog does check for their required functions.

**Comment by portante** [comment]
For `jmap`/`jstack` there does not appear to be a good answer on what package to check for because there are multiple `java*-openjdk-devel` packages (Fedora 30 offers `java-1.8.0-`..., `java-11-`..., `java-latest-`..., and `java-`...).

For `rabbit` that is usually used in an OpenStack  environment, as RHEL, CentOS, and Fedora don't ship it apparently.

**Comment by ndokos** [comment]
The problem with the datalog check is that you don't find out until after the run is finished. There is really no fool-proof way to check: we check at tool registration time, but many people keep the registration "for ever" and the packages may disappear under them during that time.

Maybe the thing to do is to just provide a best-effort checker: we make it table-driven so we can add/delete/change easily to a central location. It will only work in a given environment, but it could be made easily adaptable (we can have the table as part of the server deployment e.g. so if the client knows how to send results then it would know how to query the table). Then a user could add a call to the checker in their script and exit on error, avoiding the "wasted" run.

**Comment by portante** [comment]
With the Tool Meister work we'll have the proper infrastructure to add a check for the tool's environment before they run, so that the Tool Meister can notify the user.

But the policy for what to do when a check fails still needs to be offered to the user because whatever decision the pbench-agent make will be wrong in some instance.
