### ISSUE TITLE
Require pyesbulk 1.x until 2.x code can be fixed

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1924]
Looks like pyesbulk 2.x breaks the pbench code base.  All unit tests for the server are failing.

We'll likely need to backport this to 0.70 as well.

**Comment by portante** [comment]
Tracking the final fix in issue https://github.com/distributed-system-analysis/py-es-bulk/issues/3.

**Comment by dbutenhof** [comment]
I was going to take a quick look at the problem first to see why it's happening now; but I've got to wait for a clean .71 COPR server build. Yeah, I'll try changing the requirement first.

**Comment by dbutenhof** [comment]
I just built a fresh 0.71 pbench-server RPM off `master`, installed it onto my VM, and ran it against `pyesbulk 2.0.1`. And it worked just fine...

And in that instant, I remembered exactly what was wrong.

The problem is that in the unit test environment, we're running against a _mock_ Elasticsearch object, which doesn't have a normal Python module path.

This isn't a product problem; it's just a unit test problem. I added the fallback to `elasticsearch` to get the Pbench unit tests to work in my new code; but that fallback is wrong for the old code because we'd somehow have to figure out how to infer `elasticsearch1` instead.

The only practical pyesbulk "fix" I can imagine would be to try to import either `elasticsearch` or `elasticsearch1` and fall back to the other if it fails. That's not foolproof, because there's no reason you can't have both installed, and the first guess might be wrong.

I need to think about this; but for now, I think just specifying `pyesbulk==1.0.0` in the 0.70 `requirements.txt` is the proper solution, and I'm not 100% convinced it's worth trying to "fix" `pyesbulk` for a Pbench unit test peculiarity... unless I can think of something more nearly foolproof.
