### ISSUE TITLE
Tool Meister working directory on remote hosts not being cleaned up

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2085]
When the Tool Meister is run on remote hosts, its working directory is created in the `pbench_tmp` directory as specified by the `pbench-agent.cfg` file.

When the Tool Meister exits, it should remove its working directory, but that does not appear to be happening.

We should also consider `tar`ing up that directory and sending its contents back to the controller to be stored with the results before it is cleaned up and removed.

**Comment by npalaska** [comment]
I have few observations and questions on this issue:

Case 1 (When we have only transient tools):
1. `init_tools` of the tool meister sets up the temporary directory for the persistent tools to store its data.
2. However, the transient tools dont use this temporary directory created by the `init_tools` instead they use another temporary directory that is created by the `start_tools` which actually starts the transient tools.
3. If we don't have any persistent tools registered then tmp directory created by the `init_tools` would be empty.
4. The tmp directory created by the tool meister is only removed when the `send_tools` is called which internally calls `_send_directory`.
4. Now if we only have transient tools registered the above empty tmp directory (created by `inti_tools`) doesn't get cleaned up after the `send_tools`. (Because `send_tools` is invoked after the `stop_tools` which only gets invoked for transient tools, for the persistent tools there is no start and stop, instead we have init and end)
5. Therefore if we only have transient tools then at any given time on remote there are 2 tmp directories gets created by the tool meister (one by the init_tools and one by the start_tools). The one created by the `start_tools` (the correct tmp directory for the transient tools) gets cleaned up after the `stop tools` is called and we are left with an one empty directory (created by `init_tools`)

Mitigation: Only create temporary directory in init_tools when we have at least one persistent tool registered otherwise don't create it in the `init_tools` let `start_tools` handle it.

Case 2 ( When we have both transient and persistent tools):
1. If we have both persistent tools and transient tools then we need to create a tmp directory in the `init_tools` (Because that's when we start the persistent tools data collection)
2. This is the tmp directory that persistent tool uses to store std_err and std_out files of its execution on remote host such as `tm-node-exporter-start.err` and `tm-node-exporter-start.out`.
3. However, when the `end_tools` is called we are not cleaning up the directory that was created by the `init_tools`.
4. For the persistent tools we dont send any _tool data_ per se like transient tools but we send scraped data every certain interval over the `tool-data-sink` to the controller, where `tool-data-sink` store all persistent tool data as a tar file.
5. When the `end_tools` is called we stop the persistent tool data collection but the persistent tools tmp directory remains there because the tool data sink doesn't remove it on the remote host.

Question is how do we want to handle this case?
1. Remove tmp directory created by the `init_tools` of the tool meister inside `end_tools` along with any std_out and std_err data that maybe there for the persistent tool (At this point we already have tar file with persistent tool data on the controller).
2. Tar up the std_out and std_err files of the persistent tool and send them to the controller and what should be the appropriate directory where this tar file should land? 
3. If we decide to send persistent tools as tar file we may have to make changes the existing approach of the tool meister where we only send "tool-data" for the transient tools because the persistent tool data collection is happening via tool-data-sink at every certain interval?

@portante @ndokos WDYT?

**Comment by dbutenhof** [comment]
1. We should definitely clean up our directories;
   2. I don't see a point to having separate temp directories here;
   3. If we're generating artifacts on the remotes, we should preserve them
   (and probably echo them back to the controller) for observability

**Comment by ndokos** [comment]
I think the separate directories are there for exactly the reason that @webbnh pointed out, so I think we should keep the separate directories and do the cleanup symmetrically: looks to me that `end_tools` is the symmetrical method to `init_tools`, so that's who should be doing the cleanup.
