### ISSUE TITLE
It looks like the server is returning different responses for bad username and bad password

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2148]
It looks like we're returning different responses for bad username and bad password (same message, but different statuses).  I don't think we want the user to be able to distinguish between them.

_Originally posted by @webbnh in https://github.com/distributed-system-analysis/pbench/pull/1937#r600751826_

**Comment by webbnh** [comment]
Interestingly, [Flask may be doing the same thing](https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/ccf98aa0fe1c2458b51c3aaed5075f2e0e943d94/flask_httpauth.py#L150).

**Comment by npalaska** [comment]
@webbnh interesting, btw its not flask but an author of the `Flask-HTTPAuth` package. When I wrote that status code I followed https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401, it says 401 is for when the request lacks valid authentication credentials (such as bad password). 403 is forbidden and re-authenticating will make no difference (because we dont have such a user)

**Comment by portante** [comment]
Based on https://stackoverflow.com/questions/32752578/whats-the-appropriate-http-status-code-to-return-if-a-user-tries-logging-in-wit, we should be always returning a `401` stating "bad user or password", but not indicating which.

403 is for a operation that is attempting to execute some action requiring access, but is denied (either because the client is not authenticated, or is authenticated but the authenticated user does not have access).
