### ISSUE TITLE
Wrong COPR repo in README

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#220]
README.md refers to https://copr.fedoraproject.org/coprs/portante/pbench-agent/

**Comment by lukas-vlcek** [comment]
Actually, this has been fixed in https://github.com/distributed-system-analysis/pbench/commit/ef3f12bfad85d777006993ddb302ffec8ec220f3 and link is now pointing to https://copr.fedoraproject.org/coprs/ndokos/pbench/ which led me to the following installation instructions:

    # $ uname -a
    # Linux [...] 4.3.4-300.fc23.x86_64 [...]
    wget -O /etc/yum.repos.d/pbench.repo \
      https://copr.fedorainfracloud.org/coprs/ndokos/pbench/repo/fedora-23/ndokos-pbench-fedora-23.repo
    yum install pbench-agent

So may be this issue can be closed?

**Comment by ndokos** [comment]
Fixed in PR #223 and in the github pages.
