### ISSUE TITLE
Why are we able to create a duplicate auth token?

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2333]
Why are we able to create a duplicate auth token?

We should never be able to create a duplicate auth token.  Let's fix the code so requesting an auth token after having provided the proper credentials provides a new auth token.

We can't hand out previous auth tokens, and we should be some kind of rate-limit on creating them.

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench/pull/2329#discussion_r637344631_

**Comment by webbnh** [comment]
As I understand it, the token generation includes the current time as an input, but the time is updated with a limited granularity (0.1s?), and so two requests for a token within the same time granule produce the same token value.  The attempt to record the second token in the database fails with a constraint error, since we require the token to be unique (in the database), and this error is reflected to the user.

Given that the token is provided in response to the same valid credentials, I personally don't see any reason why responding with the same token value would represent a problem.  What drives the requirement (if indeed we actually have it...) for not creating/returning duplicate tokens?  Is it important to have distinct tokens if the requests come from the same user?  (If so, why?)

If necessary, we could probably have the server wait until the next clock tick and retry if the token generation produces a duplicate, or we could add some sort of sequence number, but I don't see the need.

**Comment by dbutenhof** [comment]
One potential problem in allowing duplicate tokens in the database is that we could break a negative authorization test. That is, session A and session B logging in using the same user (e.g., a "test" functional test user) might generate the same token. One test logs out and attempts another access using the token to validate that it fails ... only it doesn't fail because the duplicate is found. The lifetime of the authorization token is important, not just the value, and it's testable. (Similarly, if we only store the token once in the DB, then one test run logs out and legitimate queries in the other test session start failing because we deleted it. And reference counting doesn't help because it still keeps "session A"'s token "live" when "session B" logs out.)

We can finesse this in tests by somehow auto-generating a unique username (or set) in the test script that won't ever be shared by concurrent test sets, (we may need to do this anyway in order to do user registration/deletion tests); but it can certainly happen for real usage, too.

I suppose that forcing uniqueness in some way, either with a sequence number hack or by waiting is a possibility. Another would be to simply throw a random number into the payload routinely. I'd love to know how "industrial strength" user management packages handle this, because everyone's got to do this somehow.

**Comment by npalaska** [comment]
+1 on returning the same token if the 2nd request attempt is in the same time granule without actually storing the duplicate token in our database, we could just return the same token. 

> One potential problem in allowing duplicate tokens in the database is that we could break a negative authorization test. That is, session A and session B logging in using the same user (e.g., a "test" functional test user) might generate the same token. One test logs out and attempts another access using the token to validate that it fails ... only it doesn't fail because the duplicate is found. The lifetime of the authorization token is important, not just the value, and it's testable. (Similarly, if we only store the token once in the DB, then one test run logs out and legitimate queries in the other test session start failing because we deleted it. And reference counting doesn't help because it still keeps "session A"'s token "live" when "session B" logs out.)

What if we dont store the duplicated token in our database, we could just return the same token if we encounter an integrity error, right?

**Comment by portante** [comment]
Webb has described the technical reason why we get a duplicate token:

> the token generation includes the current time as an input, but the time is updated with a limited granularity (0.1s?), and so two requests for a token within the same time granule produce the same token value.

Yet:

> we require the token to be unique (in the database),

With the problem being that:

> this error is reflected to the user.

It seems the reason for a unique token on each request is tied to tracking and use.  We can't do this right now, but ideally a token derived for the CLI use should not be the same as the token for a logged in user.  If I have two browser sessions that log in at the same time, do we really want both sessions to have the same login token?

I'd like to propose we make four changes going forward:

 * Add additional metadata about the source of requested token (IP address, user-agent header, time requested, role (CLI gen-token, Browser login, etc.)
 * Only allow CLI tokens for upload API, login tokens for browser operational, etc.
 * Ensure all tokens are unique and recorded separately
 * Add a server side CLI-based client to list the token and revoke tokens

**Comment by dbutenhof** [comment]
> What if we dont store the duplicated token in our database, we could just return the same token if we encounter an integrity error, right?

It's not just the value of the token that's important, but its life cycle across login/generate to revoke. If we share a token across two logins with different lifetimes, the first to log out implicitly invalidates _both_ sessions and will cause unexpected and undesirable errors in the other. (Or else it doesn't invalidate the token, and a functional test would complain that the token remains valid after logout, which is equally a bug.)

We need better token generation. Maybe this is the time that JWT no longer serves our needs, or maybe we just hack in some other context to ensure uniqueness.

For example, we could generate a unique UUID string from a random number, or from a random number xor-ed with some server and/or client data; Pete's comment touches on this as "additional metadata".

**Comment by npalaska** [comment]
I think It is possible to generate a completely different JWT token irrespective of the time granularity if we set the "jti" (JWT ID) claim ([spec](https://tools.ietf.org/html/rfc7519#page-10)) as a unique random number. I think this will generate a completely different payload everytime it is invoked and as long as the payload is different, the JWT token will be different, I will try to experiment with it.

**Comment by webbnh** [comment]
If a token indicates that a given user is authenticated and authorized, then I think returning duplicates is fine -- the issue with the time is really around being able to determine when a token has expired -- as Dave indicated, if we really want the token to be unique we should be using something more unique than the time.

If a token indicates a session, then we need some way of telling two instances of the same authorized user apart from each other.  And, more importantly, when we get to the point of _renewing_ tokens, we'll need some way to determine whether a renewal request is coming from the same session as the creation (or previous renewal) request.

Given that we're maintaining a database of tokens, it's not obvious to me that they need to be unique.  That will depend heavily on what the renewal process looks like.  If the same user has multiple sessions with duplicate tokens, then it's entirely possible that token renewal will work seamlessly in each of the two sessions.  It's also possible that deleting the token in one session will simply trigger a renewal in the other session.

> ideally a token derived for the CLI use should not be the same as the token for a logged in user.

We need to take some care with the terminology:  we have an agent/client-side CLI as well as a server-side CLI.  Presumably Peter is talking about the client-side CLI, here, since the server-side CLI doesn't use tokens, but I think it bears pointing out explicitly.

That said, I disagree.  There is no difference, from the server's perspective, between a "CLI" and a "browser"...or, at least, there shouldn't be.  That is, there could be an arbitrary array of clients -- our Dashboard, our CLI, others' web-clients, other data sources/concentrators, gateways, other sorts of agents -- and we shouldn't need to know anything about their characteristics:  we only need to know that the user is authentic and that it is authorized for the request being made.

So, presumably, we will want to have different tokens for upload vs. visualization (as well as other categories of requests).  But, that's different from knowing that a given token is for/from a CLI tool or a browser application.  We can handle this by attaching a role to the token.

Using metadata about the how the token was created will be counterproductive, because it will prevent us from doing things like allowing a user to generating a token via the Dashboard (instead of via `pbench-generate-token`) and use it in a CLI command like `pbench-results-move`.  All that the server needs to know is whether the token (via the role) authorizes the request; how the token was created is immaterial -- we only need to be able to confirm that the token is valid.

And, I don't think this requires that a token be unique.  I think we need to be able to create tokens, have them expire, have a process for renewing them (eventually), be able to validate them, be able to extract the user identity and authorization (role) from them, and be able to revoke them.  I don't see any requirement for uniqueness there, and anything related to metadata can be maintained on the server side (not in the token) and should only be used for statistical purposes.

I think that we can minimize the issues that we think that duplication is going to cause.  Under the present scheme, it is highly unlikely that a human user (other than Peter  ;-) ) will encounter token duplication.  For non-human users, I believe that we can avoid the problem easily by serializing the tests or by using multiple usernames.

(At this point, I think we should be chasing the details of how Peter is triggering a duplication rather than worrying about whether the problem should exist.)

**Comment by dbutenhof** [comment]
Lots to unpack here, but a couple comments:


Looking at __"as Dave indicated, if we really want the token to be unique we should be using something more unique than the time"__ and __"Using metadata about the how the token was created will be counterproductive"__ ... in a way, these are contradictory, but I also think I understand where Webb is coming from, and it's a good point. I'm not sure about Peter's original intent in referencing "metadata" but in my vision, although I copied the term, "metadata" was a poor choice. I didn't mean that in terms of "tracking and checking" out of band context related to the token ... my intent was to use it as a source of additional entropy to remove the chances of multiple tokens for the same user within a narrow temporal band coming up identical. I would agree absolutely that the server should never make decisions about handling a token based on its origin. (E.g., if one component of the token is a sequence number, there can never be duplicates.)

Again, I have always favored the idea of generating a unique/random UUID value as a token. We don't need a timestamp, either for creation or expiration, since we're tracking it in the DB ... and the __entire__ purpose of JWT is to avoid having to track in a database (unless you want to log out, where JWT completely breaks down and forces bizarre artifacts like a blacklist DB).

> If a token indicates a session, then we need some way of telling two instances of the same authorized user apart from each other. And, more importantly, when we get to the point of _renewing_ tokens, we'll need some way to determine whether a renewal request is coming from the same session as the creation (or previous renewal) request.

> Given that we're maintaining a database of tokens, it's not obvious to me that they need to be unique. That will depend heavily on what the renewal process looks like. If the same user has multiple sessions with duplicate tokens, then it's entirely possible that token renewal will work seamlessly in each of the two sessions. It's also possible that deleting the token in one session will simply trigger a renewal in the other session.

Again, we need to track the life cycle of tokens not just the value, and it can't ever be true that a previous token value remains valid, or "logout" tests will fail.

Yes, if we do short expirations and renewal, then blowing away both sessions when one logs out might be fine, but we're not close to that model yet. And letting one session implicitly extend another because they got identical tokens isn't a good idea, either; again, that can lead to unpredictable failures in testing (or real life) situations where one session shouldn't have access but does due to  its "twin".

We avoid all this by making them unique. And including timestamps is absolutely pointless in our model unless it's _adding_ entropy (which its clearly not), since the DB row provides any metadata we need. There's similarly no point in encoding username in the token. We just need a completely random unique string ... like a UUID.

> > ideally a token derived for the CLI use should not be the same as the token for a logged in user.
> 
> We need to take some care with the terminology: we have an agent/client-side CLI as well as a server-side CLI. Presumably Peter is talking about the client-side CLI, here, since the server-side CLI doesn't use tokens, but I think it bears pointing out explicitly.
> 
> That said, I disagree. There is no difference, from the server's perspective, between a "CLI" and a "browser"...or, at least, there shouldn't be. That is, there could be an arbitrary array of clients -- our Dashboard, our CLI, others' web-clients, other data sources/concentrators, gateways, other sorts of agents -- and we shouldn't need to know anything about their characteristics: we only need to know that the user is authentic and that it is authorized for the request being made.

Yes; absolutely. A token authenticates a given client's access to server capabilities. Period. It doesn't make any difference how that's presented to the server. (Though taking a `pbench-token-generate` intended to `PUT` a dataset and using it for a dashboard query won't get you far, that's because the DB associates that token with a PUT-only role, not because it was generated by the agent CLI.)

> I think that we can minimize the issues that we think that duplication is going to cause. Under the present scheme, it is highly unlikely that a human user (other than Peter ;-) ) will encounter token duplication. For non-human users, I believe that we can avoid the problem easily by serializing the tests or by using multiple usernames.

Really, Webb? You're going to argue that we can ignore a known timing window now on the assumption that nobody will ever hit it in release? Wow. How quickly they forget. ;-)

**Comment by webbnh** [comment]
I think Dave and I are pretty much on the same page.  (There are some small wrinkles, but I expect that we would quickly come to agreement on them, so I won't burden this thread with that process, except to point out that we don't have PUT-only tokens yet...but I'm sure we will have them just as soon as Nikhil implements them.  ;-) )

As for ignoring a known timing window....  That problem fails in a secure way, so I think what we're concerned with is a usability problem.  For testing purposes, I think we can work around it.  For other non-human access, I don't think the problem exists, but, to the extent that it does, I think whoever hits it can work around it using the same techniques that we will employ in the tests.  For human access, I don't think the problem will occur -- other than for Peter -- with a frequency which will be high enough for anyone to notice or reproduce.  And, for Peter, I think we need to regard this as an implementation or deployment bug which needs to be found and fixed before release.  (That is, I don't think that what Peter saw indicates a design or architecture problem -- I think it's something like a proxy configuration issue.)

So, yeah, I think we should get rid of time-based tokens, but probably not for 0.71 or even 0.72.

**Comment by portante** [comment]
No longer relevant with our transition to using keycloak.
