### ISSUE TITLE
pbench-clear-tools potential potholes

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2337]
I did some experiments with the current (0.71) version of `pbench-clear-tools` and was surprised with many of the outcomes.

The setup for every test in the following table was the same:
```
pbench-register-tool --group foo --name iostat
pbench-register-tool --group foo --name mpstat
pbench-register-tool-set 
```
so we always start with two tool groups (`default` with the default tool set and `foo` with `iostat` and `mpstat`.

Here's the result of calling `pbench-clear-results` with the indicated options:

| option                                    | result                                            | my expectation                   | comments                     | 
| -------------------------------------- | ------------------------------------------- | -------------------------------- | ---------------------------- | 
|                                                | clear default                                  | clear all groups                 |                              |
| –group=foo                            | clear foo                                        | clear foo                  | X: All tools removed message | 
| –group=default –group=foo  | clear foo                                         | clear both groups                | X: last one wins             | 
| –name=mpstat                      | clear mpstat from default                | clear mpstat from all groups     |                              | 
| –group=default –name=mpstat            | clear mpstat from default | clear mpstat from default        |                              | 
| –group=default –group=foo –name=mpstat | clear mpstat from foo     | clear mpstat from both groups    | X: last one wins (group)     |
| –name=mpstat –name=iostat              | clear iostat from default     | clear both tools from all groups | X: last one wins (name)      |
| --group=foo –name=mpstat –name=iostat   | clear iostat from foo     | clear both tools from foo        | X: last one wins (name)      |

There are no tracebacks thankfully, but there is one bad message: "All tools removed" when all the tools in a group are removed even though there are tools in another group. The CLI (here and probably in other cases) seems to accept multiple entries for an option but uses a "last one wins" policy, so the only way to remove all tools from every group is to loop over every group.

All of this is probably OK if the user has a single group named 'default`, but for any more complicated situation, I find the handling confusing.

- I think the bad message should probably be fixed to indicate the group that was cleared. 

- Should we signal an error for multiple entries of a single option (IOW, do not put ourselves in the position of having to enforce "last one wins" or similar)?

- Should we provide a way to clear a tool from all groups?

- Should we provide a way to clear all tools from all groups?

**Comment by dbutenhof** [comment]
If there's a case where we think we ought to support multiple instances of
an option, like --group, Click can do that
<https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments>.
Then the code can loop over all the values. Just taking the last is bad.

It does seem there should be a way to clear all groups and start from
scratch. I'm not sure of the best syntax. Something like --group ALL,
maybe, although adding a reserved token into group name space is a bit
awkward, I've seen a lot of similar commands that support "all" and "none"
keywords in lists.

**Comment by webbnh** [comment]
Last-one-wins is a pretty common behavior for simple command line parsers.  There are even scenarios in which this is considered a feature (because it allows "upstream" command line definitions to be partially overridden by concatenation).  That said, I'm not in love with it.  But, an alternative to accepting multiple instances of a given option would be to allow a single instance which accepts a list (e.g., `--group=foo,default`).

Having the command target all groups when the `--group` switch is omitted is probably a bad idea.  I think other commands which accept the `--group` switch treat the absence of the option as a synonym for `--group default`.  With that bit of culture in place, having that behavior here makes good sense (and the "all tools" message isn't quite so weird, knowing the context, although adding the group name to it wouldn't hurt).  If we really want an option for targeting all groups, we should probably add a separate one for it (like `--group-all` or `--all-groups`).

As for your questions, what is the need or use-case for clearing a single tool from multiple groups (particularly being able to do so in a single command)?

I can imagine a desire to delete all existing groups, but listing them and manually deleting them one by one doesn't seem so bad (that is, I think the cost to us to implement, test, and maintain a "delete-all" isn't exceeded by the value to our users of easing this presumably rare effort).

**Comment by portante** [comment]
It is not clear that we should change the behavior from "last one wins" to "parameters add up".  Perhaps we could consider issuing a warning message to let the user know that only the last parameter value of a parameter is accepted, and add support for comma-separated lists of `--name` and `--group`.

**Comment by webbnh** [comment]
By the way, just as a heads up, I've strayed into making some changes to `pbench-clear-tools`.  I was working on `pbench-list-tools` and testing that required using `pbench-clear-tools`, and then I got sucked into the maelstrom.  My changes are in #2612, and they are mostly centered around fixing the help text (which appeared to be cut-and-paste from `pbench-list-tools` without much in the way of changes 😀), but then I started picking lint and that led to other changes, like added/enhanced diagnostics output for errors/edge-cases.  I don't think I've made any really significant operational changes, but we'll find out when people review the code.  😉  (My changes almost didn't require changes to the unit tests, so....)

**Comment by webbnh** [comment]
> there is one bad message: "All tools removed" when all the tools in a group are removed even though there are tools in another group.
> [...]
> I think the bad message should probably be fixed to indicate the group that was cleared.

Apparently great minds think alike (and so do ours, @ndokos...) -- with my changes this is now the output:
```
$ pbench-clear-tools --group=foo
Removed "iostat" from host, "6e8184bd9ff2", in tools group "foo"
Removed "mpstat" from host, "6e8184bd9ff2", in tools group "foo"
All tools removed from group "foo" on host, "6e8184bd9ff2"
```
If that's acceptable, we can check this item off the list.

**Comment by webbnh** [comment]
Note, however, I think there is a bug hiding in the code, which I haven't been able to spot:  despite the assertion that "All tools were removed", the tool directory (e.g., `/var/lib/pbench-agent/tools-v1-foo`) is _not_ removed, despite it being empty.
