### ISSUE TITLE
pbench-uperf complains about missing tool output directory

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2347]
Version: `pbench-agent-0.71.0-185g5527f23f1.noarch`

```
# pbench-uperf -t bidirec -S vales2.slevarna.tpb.lab.eng.brq.redhat.com
.
.
.
iostat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/iostat', missing
iostat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/iostat', missing
mpstat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/mpstat', missing
iostat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/iostat', missing
mpstat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/mpstat', missing
perf: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/perf', missing
iostat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/iostat', missing
mpstat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/mpstat', missing
perf: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/perf', missing
pidstat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/pidstat', missing
iostat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/iostat', missing
mpstat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/mpstat', missing
perf: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/perf', missing
pidstat: WARNING - postprocess - tool output directory, '/var/lib/pbench-agent/uperf__2021.06.08T12.46.44/3-tcp_bidirec-1B-64i/sample2/tools-default/vales1.slevarna.tpb.lab.eng.brq.redhat.com/pidstat', missing
```

**Comment by portante** [comment]
This is because the `pbench-sysstat` RPM is not installed.

**Comment by riya-17** [comment]
```sar: pbench-sysstat-12.0.3 is not installed
[error][2021-12-09T08:34:02.013891820] Failed to install tool sar (/opt/pbench-agent/tool-scripts/sar --install "--interval=3")
iostat: pbench-sysstat-12.0.3 is not installed
[error][2021-12-09T08:34:02.103126928] Failed to install tool iostat (/opt/pbench-agent/tool-scripts/iostat --install "--interval=3")
mpstat: pbench-sysstat-12.0.3 is not installed
[error][2021-12-09T08:34:02.165326306] Failed to install tool mpstat (/opt/pbench-agent/tool-scripts/mpstat --install "--interval=3")
pidstat: pbench-sysstat-12.0.3 is not installed
[error][2021-12-09T08:34:02.227132366] Failed to install tool pidstat (/opt/pbench-agent/tool-scripts/pidstat --install "--interval=30")
proc-vmstat tool is now registered in group default
proc-interrupts tool is now registered in group default
turbostat: kernel-tools is installed
turbostat tool is now registered in group default
perf: perf is installed
perf tool is now registered in group default
```


I took a look at it. it seems like `pbench-register-tool-set` or `pbench-register-tool` already takes care of checking whether pbench-sysstat is installed or not.

**Comment by ndokos** [comment]
Yes, `pbench-sysstat` is not installed automatically: it has to be installed manually or through the playbook, I need to update the documentation to make this explicit.

**Comment by ndokos** [comment]
@portante: the absence of `pbench-sysstat` does not explain why `perf` is having the same problem, right? But maybe that too was not installed.

**Comment by ndokos** [comment]
@riya-17: are you sure `pbench-register-tool-set` checks properly? I did an experiment with 0.71.0-13g7b02500fa (the latest available in the `pbench-test` repo) and `pbench-register-tool-set` says:

```[root@dhcp31-138 ~]# pbench-register-tool-set --toolset=legacy
"iostat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"mpstat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"pidstat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"proc-interrupts" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"proc-vmstat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"sar" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"turbostat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
"perf" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
```
Do I need to build an RPM based on current code?

**Comment by riya-17** [comment]
I will check it again and revert here.

**Comment by riya-17** [comment]
> @riya-17: are you sure `pbench-register-tool-set` checks properly? I did an experiment with 0.71.0-13g7b02500fa (the latest available in the `pbench-test` repo) and `pbench-register-tool-set` says (and `pbench-sysstat` is _not_ installed):
> 
> ```
> "iostat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "mpstat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "pidstat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "proc-interrupts" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "proc-vmstat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "sar" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "turbostat" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> "perf" tool is now registered for host "dhcp31-138.perf.lab.eng.bos.redhat.com" in group "default"
> ```
> 
> Do I need to build an RPM based on current code?

@ndokos I am seeing the same output. `pbench-register-tool-set` is not throwing any error if `pbench-sysstat` is not installed.

**Comment by riya-17** [comment]
We will have to add a check for it. Shall I add that check?

**Comment by ndokos** [comment]
`perf` is *NOT* a dependency of the `pbench-agent` RPM so we might have the same problem. OTOH, it seems that RHEL[89] install `perf` by default (although I need to double-check).

**Comment by ndokos** [comment]
@riya-17 and I went through the code: the Tool Meister gets an "init" message  and checks for persistent tools: first checking presence (complaining and failing if the executables are not found) and then starts them. But transient tools are not checked at all. My suggestion would be to add a transient tool checking routine (just loop over the transient tools, calling `find_executable()` for each one`: if they are all there, return success; otherwise, record the ones that it doesn't find in a message, sending a status back to be reported and return failure). The Tool Meister routine called on "init" is `init_tools`: we can call the transient tool checking routine when it begins and return failure immediately if that fails; otherwise, we drop down to the persistent tool checking and set up. Actually, we might want to do the checking of *all* the tools first and only if that succeeds do we proceed with the setup: that way, we can generate a comprehensive report of all the failures.

We also need to check the plumbing on the higher layers to make sure that they respond to failures properly, but I think that's OK. 

@portante: WDYT?

Unrelated to the above, but just adding it here so I don't forget: `pbench-start-tools` is called e.g. from `pbench-user-benchmark` but its return status is not checked (ditto for `pbench-stop/send/postprocess-tools` after the benchmark run). Do we need to check?

**Comment by portante** [comment]
All tools have their installs recorded in the Tool Data Sink at: https://github.com/distributed-system-analysis/pbench/blob/main/lib/pbench/agent/tool_data_sink.py#L1042.

The individual Tool Meisters run each tool's `--install` switch by default.

So if a tool does not have a `--install` check, then it won't matter.

But I am pretty sure `iostat`, and other default tools, have `--install` checks.

Those checks are all recorded in the Tool Data Sink.

We just need to make sure we pass the results back to the `pbench-tool-meister-start` so that it can check and fail the start.

What I think is missing is that for a given persistent tool (today just node_exporter, dcgm, and pcp), there should be a `--install` check performed on each Tool Meister instance, AND the Tool Data Sink needs to verify that it has the requisite collector (Prometheus or PCP) installed before the Tool Data Sync acknowledges that it has started.
