### ISSUE TITLE
Ensure the pbench-server is repeatedly deployable as by a functional test or naive developer

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2387]
Ensure the pbench-server is repeatedly deployable as by a functional test and a naive developer.

The goal is to verify behavior and generate issues as needed to cover missing functionality or behaviors.

**Comment by pravins** [comment]
Is this related with PR https://github.com/distributed-system-analysis/pbench/pull/2585 ?

**Comment by pravins** [comment]
Agree. Thanks @webbnh for the explanation.

**Comment by webbnh** [comment]
I believe that what we set out to do (_enable_ development and functional testing) has been achieved.  As such, I'm closing this issue.

Creating a proper functional test system built on top of this containerization will constitute a significant effort which is probably best represented in Jira rather than by keeping this issue open.
