### ISSUE TITLE
`pbench-trampoline` hardwires python3.8 component in PYTHONPATH

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2415]
So it will work on RHEL8.4, but not on F34 where we have python3.9.

**Comment by webbnh** [comment]
I noticed that some time ago, but failed to act on it (at the time, I hadn't noticed that we had access to Python3.9...) -- I apologize!  However....

For Agent-side tools, we should be replacing the trampoline approach with a `setup`-installed Click-based approach.

For Server-side stuff, these generally are not CLI-type tools, and so they shouldn't need the trampoline either.

So, what exactly is not working?  (Other than all legacy Agent tools on F34....)

**Comment by portante** [comment]
> For Agent-side tools, we should be replacing the trampoline approach with a `setup`-installed Click-based approach.

Do we use a `pbench-trampoline` on the agent side?  Isn't that code just on the server side?

Doesn't the agent side have the `PYTHONPATH` setup properly in `agent/profile`?

> For Server-side stuff, these generally are not CLI-type tools, and so they shouldn't need the trampoline either.

To remove the trampoline we'd need to move what the trampoline code does to some other common place.  But that is what the trampoline code is for ... to be the one common place so we are "DRY".

> So, what exactly is not working? (Other than all legacy Agent tools on F34....)

First, the original commit that introduced this change on the `b0.69` branch is https://github.com/distributed-system-analysis/pbench/commit/948f58f372218dfe300c80510abb43e5efad75b3.

For the `main` branch, we appear to have a problem since we don't update the `PYTHONPATH` to include the various `/opt/pbench-server` Python3 library paths we have (for the python modules the pbench-server code provides, and for the local install of `pip3` dependent modules for the given version of Python3 being used).

So ... there should be no problem with any "agent" side code on Fedora 34.

Since the pbench server code on the `b0.69` branch only supports RHEL 8, we should not have a problem since the RPM specifically says it requires python38 (yes, that is fragile, but that is the `b0.69` branch).

For the `main` branch, we need to properly fix the missing Python3 `PYTHONLIB` paths IFF we want to support Fedora 34 environments for our pbench-server installs.

**Comment by portante** [comment]
Closing this issue since the `b0.69` branch only supports RHEL 8 with an explicit `python38` RPM dependency.
