### ISSUE TITLE
pbench-agent rpm does not have dependency on pbench-sysstat

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2433]
pbench-agent-0.69.9-1ga12a9aa0f 

After installation of `pbench-agent-0.69.9-1ga12a9aa0f`  rpm `pbench-sysstat` is not installed as a dependency. I assume that this is a bug, because pbench-agent cannot be reasonably used without `pbench-sysstat`.

**Comment by portante** [comment]
This problem is tied up with the default tool set.  Ideally the default tool set would not include any `pbench-sysstat` tools so that we don't have to have a dependency on a particular RPM for tools.

But that might not be reasonable.

We really want to be able to use the `pcp` tool by default, which would be another dependency.  However, if we have the right messaging, we should properly warn the user when no tools are found that were registered.

**Comment by ndokos** [comment]
Although there are deeper issues as @portante mentions, we are not going to impose a dependency of the `pbench-agent` RPM  on `pbench-sysstat`: currently, the problem is "solved" by having the Ansible playbook install *both* the `pbench-agent` RPM and the `pbench-sysstat` RPM, but of course, that does not work if the Ansible playbook is *not* used. The ultimate resolution is that we are going to get rid of `pbench-sysstat`, but for the time being, the user is expected to either install using Ansible or install `pbench-sysstat` manually.

Closing this, but feel free to reopen if you object.
