### ISSUE TITLE
pbench-copy-result-tb crashes with exception

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2437]
pbench-agent `0.69.9-1ga12a9aa0f`

```
$ pbench-copy-result-tb /root/fio__2021.08.23T07.49.04.tar.xz
[error][2021-08-23T08:34:55.377212265] ERROR (internal): unexpected file count, 575, associated with tar ball, /root/fio__2021.08.23T07.49.04.tar.xz
```

**Comment by portante** [comment]
Unfortunately, this is due to a poorly specified interface in the help text.  The path to the tar ball needs to be in a directory named for the "controller", and it should only have in that directory a tar ball and the `.md5` file.

To fix the example in the description, one would execute the following:

```
$ CTRL_DIR=/var/tmp/$(hostname -f)
$ mkdir ${CTRL_DIR}
$ mv /root/fio__2021.08.23T07.49.04.tar.xz /root/fio__2021.08.23T07.49.04.tar.xz.md5 ${CTRL_DIR}/
$ pbench-copy-result-tb ${CTRL_DIR}/fio__2021.08.23T07.49.04.tar.xz
```

**Comment by portante** [comment]
We expect the fix to contain at least some update to the documentation to describe the behavior, and possibly an update to the failure mode to be more user-friendly.
