### ISSUE TITLE
Resolve the use of class attributes which require run-time execution data

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2443]
A comment, originally posted by @webbnh in https://github.com/distributed-system-analysis/pbench/pull/2325#discussion_r638234022, sparked a rather long and involved discussion about when class attributes vs instance attributes should be used when the attributes contain data that require a function to resolve their values.

PR #2325 used the `find_executable` method of `distutils` to resolve the paths for two executables it requires, following the same pattern of using instance variables as the `ToolMeister` and `ToolDataSink` classes use.

We should continue this discussion here, and decide on using class vs instance attributes for those attributes which require functions to resolve their values.

**Comment by webbnh** [comment]
The discussion in the PR eventually revealed a project requirement that module load and class initialization not invoke external dependencies.  (This requirement wasn't clear to me previously.)  Meeting this requirement precludes calling `find_executable()` to initialize a class attribute, and so this has to be deferred to instance initialization.

Since the original discussion was driven by how we mock the `tar` and `xz` executions, I think the rest of the discussion here is now moot.
