### ISSUE TITLE
pbench-list-tools issues (brought forward from a now-closed issue)

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2458]
These were comments by @webbnh in the now-closed issue #1504 "pbench-list-tools not finding the group members" (which was resolved by PR #2301):

> Initial investigation

>This command works OK for me (although the command produces no output...) using quay.io/pbench/pbench-agent-all-fedora-32:v0.71.0-130, so, presumably the issue here is related to something in the configuration.

>However, if I mess around with the -C switch or the _PBENCH__AGENT_CONFIG environment variable, the code responds "ungracefully" (but doesn't produce the result above).

>It would be helpful if there were command options which listed the tool names and group names which were available to be supplied to the -n and -g switches, and if those switches validated their options. (I will look into adding these.)

>(And, there's a typo in the help text for the -C switch: envrionment ==> environment.)

I'm pretty sure the typo in the 4th paragraph is fixed. The others may still be open.

**Comment by webbnh** [comment]
> if I mess around with the -C switch or the _PBENCH__AGENT_CONFIG environment variable, the code responds "ungracefully" (but doesn't produce the result above).

This  is no longer the case:  the results of such messing are now adequate.

> (And, there's a typo in the help text for the -C switch: envrionment ==> environment.)

This has been fixed.

> It would be helpful if there were command options which listed the tool names and group names which were available to be supplied to the -n and -g switches, and if those switches validated their options. (I will look into adding these.)

I concur that this isn't needed.  What I would suggest instead is making the tool more expressive in the cases where the user (i.e., me) is left wishing for them:  that is, when the tool has nothing to print out, instead of being silent it should instead issue a diagnostic message -- this will (hopefully) provide better understanding of the situation for the user...so I'm experimenting with adding this, now.
