### ISSUE TITLE
It looks like `pbench-server.cfg.example` needs some love

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2521]
Comparing [the current `pbench-server.cfg.example`](https://github.com/distributed-system-analysis/pbench/blob/f0b012df7353e401fefda6105c5a18d9cd09724e/server/lib/config/pbench-server.cfg.example) to [the config file used for last April's Jam session](http://git.app.eng.bos.redhat.com/git/perf-dept.git/tree/bench/pbench/server/staging/config/pbench-server.cfg?id=e44c386d2071b438aa7b623ae6e10e9aa9b8445f), it would seem that there's been some evolution which hasn't been reflected in the template.

### Added:
- `[DEFAULT]`
  - `realhost`
  - `token_expiration_duration`
  - `pbench-receive-dir-prefix`
  - `admin-email`
- `[sosreports]`
  - ...
- `[Postgres]`
  - ...

### Removed:
- `[DEFAULT]`
  - `bind_port`
  - `rest_version`
  - `rest_max_content_length`
  - `rest_uri`
- `[graphql]`
  - ...

So, it looks like perhaps `pbench-server.cfg.example` isn't quite useful as a template....  There are a number of options in the `pbench-server-default.cfg` file which are commented out with notations indicating that they should be provided by the config file...it seems like they should be reflected in the example file somehow.

It would probably be good to canvas the source code and see whether there are any other config options which should be added to or updated in the example file.

**Comment by dbutenhof** [comment]
Or, counter-argument: we need to formalize a strategy of what we put in the *example* for `pbench-server.cfg` vs what we just put in `pbench-server-default.cfg` and don't even bother to explicitly advertise in the customizable example.

All of the things that were removed from the example are things that we don't necessarily require to be changed for individual implementations. Of those, we definitely don't want to encourage a site to change the default API version or the construction of the `rest_uri` (which is based on the version). Maybe they will need to change the `bind_port`, but containerizing the server makes that a lot less likely. Perhaps they'll want to override the default `rest_max_content_length`; I think that's the only one of this set we might arguably want to advertise in the example.

Maybe we want to advertise and encourage overriding the `admin-email`, which is `pbench@(host)`. I expect we *don't* want to encourage overriding the token expiration, particularly as we start setting our own internal overrides based on expected role and usage. The `realhost` is only needed when `hostname` differs from `ip addr`; I'd think we probably want to clearly point that out, but I suspect it ought to be commented out in the template example file.

GraphQL is pretty much obsolete, but the current dashboard does still make calls and that definitely needs to be overridden per-site, just like Elasticsearch and `db_uri`.

I think we might have overridden `pbench-receive-dir-prefix` out of my confusion from the collision of `prep-shim` and `PUT`, which generated a few strange messages in the log; as if by changing the definition we could separate them. (Which isn't actually true, and would break everything.) In terms of the example, I think we'd want to just hide the standard setting in `pbench-server.default.cfg` and encourage people to leave it alone. But that really ought to be completely removed for 0.72 anyway as it's related to `ssh` transport and the `prep-shim` which we don't expect to support at all.

(As soon as I fix `PUT` to use my new file tree class to install incoming tarballs in the `ARCHIVE` directory directly, instead of relying on `prep-shim`, we can nuke this whole subsystem including the config settings.)

**Comment by webbnh** [comment]
My bad -- I shouldn't have implied that the only means of fixing this was changing the example file -- these issues certainly can be addressed by changing the defaults file, as well.

Nevertheless, it would be nice if someone like me could create a "typical" `pbench-server.cfg` file by copying and editing just the example file, without having to consult the defaults file to look for things to add to the config file.  (And, it might be good to make it clearer that the defaults file should not be modified -- it's just there to add and fill in things around what is specified in the config file.)

**Comment by dbutenhof** [comment]
To clarify, I think there's a genuine valid issue in here, but I wanted to quibble with the specifics of your examples. 😆 

* We ship config options in two pieces, the `pbench-server-default.cfg` which we don't really expect sites to edit, but which of course they're allowed to edit (knowing we'll overwrite it on upgrade and delete it on removal, because we own it);
* We ship the `pbench-server.cfg.example` as a basis for customizing an installation with not just the expectation that it'll be change but an absolute requirement that it be changed as we can't know backend server addresses, etc.

I would like to think that

1. `pbench-server-default.cfg` defines all the mandatory defaults, as well as things we don't expect to be changed, discourage changing, or that most admins simply don't need to see at all;
2. `pbench-server.cfg.example` can be copied to `pbench-server.cfg` and when opened in an editor will clearly show the minimum set of variable that *need* to be changed (e.g., backend servers), a few "preference" things (like the "from" email address, bind port) which are commented out with explanations that include the default value.

If they want to read `pbench-server-default.cfg` and figure out what other parameters they might want to *copy* into `pbench-server.cfg` to change, they're welcome to do that, but I suspect we'd be better off not encouraging it too much.

**Comment by portante** [comment]
Removed via PR #3100.
