### ISSUE TITLE
Address how we handle Ctrl-C (interrupting bench-scripts)

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2625]
When trying to interrupt a bench-script (`pbench-user-benchmark`, `pbench-fio`, others) often requires multiple attempts, and volumes of output are created as a result.  We really need to ensure bench-scripts can be interrupted cleanly.

**Comment by ldoktor** [comment]
Hello everybody, the problem is not only the ctrl+c, which is usually ignored and results in tons of messages and still running pbench, but it'd be nice to also properly handle killing of this process.

Alternatively it'd be nice to first detect such processes are running and warn/destroy/reuse them on second attempt. Let me share my scenario:

1. running pbench-uperf
2. it get's stuck so `kill $UPERF_PID` is used (or ctrl+c)
3. second attempt to execute the same (or following test) is issued

* In 0.69 the step (2) usually left some screen sessions behind which were relatively harmless, affecting the performance a bit but shouldn't be critical and the step (3) succeeds.
* In 0.71 the step (2) leaves `gpg-agent`, `scdaemon` and `pbench-tool-meister-start` processes behind, step (3) creates another set of those 3 processes and hangs for infinity

It'd be nice to have way to quickly restore to the previous state or at least detect the tools running and re-attach or destroy them so the testing can proceed.

**Comment by ldoktor** [comment]
Note: In version 0.69 I usually used `ctrl+z`, `ps` and `kill`-ed everything except of my shell command, which also worked well.

**Comment by dbutenhof** [comment]
This potentially covers a lot of ground. Webb recently opened #2666 and #2667 which relate to this, and more directly to the added comments on this issue from Lukas. In Webb's issues I referenced a few other related cleanup issues, including #2120, #2173, and #2174 (possibly more).

This particular issue was opened by Peter in response to comments (specifically mine, but also from Webb and Nikhil) as we began debugging assorted cross-network Tool Meister issues; and while Peter wrote it more generally I believe the entire area is too big for a single PR.

I'm going to focus work initially under this issue on direct cleanup to the tool meister code (and in particular `pbench-tool-meister-start` and `pbench-tool-meister-stop`) to ensure that errors (and interrupt) result in:

- [ ] If tool meister clients have been started, ensure that we attempt to shut them down gracefully through existing TDS message protocols.
- [ ] If we can't be sure each TM client has shut down, "hunt and destroy" via `ssh` (essentially #2120)
- [ ] If we orchestrated Redis/TDS creation, gracefully request termination
- [ ] If they don't confirm exit (e.g., they're hung or otherwise misbehaving), kill them (#2173, #2174 
- [ ] Clean up local `pbench_run` artifacts, although we need to decide how far to go with this. (E.g., there may be useful logs in the `<run-directory>/tm`; do we save them, do we preserve possible partial collected results under `<run-direcory>` ... or do we delete the entire thing.)

Other benchmark tools, including `pbench-fio`, `pbench-uperf`, `pbench-user-benchmark`, and `pbench-run-benchmark` should be invoking `pbench-tool-meister-stop --interrupt` on ^C via a language-specific interrupt handler (Python `KeyboardInterrupt`, bash `SIGINT`, etc.) in addition to any benchmark specific cleanup (like killing `fio` or `uperf` servers it starts). So additional PRs can build benchmark tool robustness on top of improved tool meister behaviors.

**Comment by ldoktor** [comment]
Thank you, looking forward to this as recently I needed to run RHEL9/pbench-0.71 bigger job and I had to manually intervene a couple of times due to hanged script likely hanged by TM (due to time constraints I have not investigated further but as soon as I have some spare time I mean to re-run them and investigate (some were probably caused by crashed VMs, some just stalled with fio jobs still present but not consuming any IO/cpus for hours). Note I haven't observed anything like this in 0.69 so far running the same set (on RHEL8 as well as RHEL9).

**Comment by dbutenhof** [comment]
In comparison with 0.69, Tool Meister adds a bunch of daemon processes across the nodes, which makes cleanup -- particularly in error cases -- a lot more ... "fun". 😆
