### ISSUE TITLE
Whither `/var/lib/pbench-agent`?

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2665]
In a fresh, RPM-based installation of the Pbench Agent (such as one might find in the `quay.io/pbench/pbench-agent-all-centos-8:beta` container), the default configuration points `pbench_run` at `/var/lib/pbench-agent`...but that directory doesn't exist, yet:
```
[root@c63f47495b69 /]# pbench-register-tool --name=vmstat
[ERROR] pbench run directory, /var/lib/pbench-agent, does not exist
```
The question is, is this a bug or a feature?

The problem is, ostensibly, the user should be allowed to put the "run directory" anywhere s/he wants and then point to it via the `pbench_run` environment variable or by configuring `pbench-agent:pbench_run` in their config file.  It is only if no other provision is made that the value ends up being `/var/lib/pbench-agent`.  So, there's probably a reasonable argument to be made that _installation_ should not create the directory and, in fact, that the directory shouldn't be created until some Pbench command is run...and, possibly, not even then!

But, a user running a Pbench command (as above) and having it fail because they didn't manually create the run directory creates a poor user experience (particularly, if the default is in a system directory which is not normally user writable).

Still, we don't really want to put Pbench in the position of creating the directory on the fly:
- if we think that the directory doesn't exist because the user made a typo when specifying the location, then we'll create a new one in the "wrong place";
- if we create a directory in any location other than the default, then we won't know to remove it if pbench is uninstalled; and,
- if the invocation happens to be privileged, we don't want pbench to become a vector for a security attack.

So, what to do??

But, most of all, our behavior should be consistent.  E.g., given the above, this is a problem:
```
[root@c63f47495b69 /]# ls -ld /var/lib/pbench-agent; pbench-list-tools; ls -ld /var/lib/pbench-agent
ls: cannot access '/var/lib/pbench-agent': No such file or directory
No tool groups found
drwxr-xr-x. 3 root root 35 Mar  8 00:11 /var/lib/pbench-agent
```
(Yeah:  `pbench-list-tools`, unlike `pbench-register-tool`, when run as root, will create `/var/lib/pbench-agent` if it doesn't exist.)

**Comment by npalaska** [comment]
I recently encountered this problem while I tried to run the TM after my fresh installation of the pbench-agent on a new VM. I created the directory manually and that fixed the problem. However, I had to export an environment variable `export _PBENCH_TOOL_MEISTER_CLIENT_LOG_LEVEL=debug` to figure out what was going wrong. 

I dont think we should be expecting the end user to tune the pbench log levels to debug the TM issues, I think it is pbench-agent's job to to create that directory if it need to store the temporary data over there.

**Comment by webbnh** [comment]
Debugging distributed execution is a problem unto itself (and, I'm hoping that the fruits of Dave's and Peter's current efforts will go a considerable way toward addressing that).

I expect that the creation of the "run directory" on _remote_ nodes should be handled by the TM, one way or another; to the extent that that is not happening now, I think it's a bug.

It's the creation of the directory on the node where the user explicitly installed Pbench which is trickier.

**Comment by dbutenhof** [comment]
> I dont think we should be expecting the end user to tune the pbench log levels to debug the TM issues,

We don't expect end users to be debugging Pbench; that's our job. But it needs to be a lot easier and more consistent than it currently is. The specific problem *I'm* currently trying to attack is that if you're really using a remote tool meister client, the environment variables don't even help because there's no mechanism to reflect that across the `ssh` that starts them. I've been toying with ways to pick up the early `print` and `logger` messages before we connect to the TDS and start up the `RedisHandler` log reflector. (I would have put that issue off for later, but it's giving me pains trying to figure out what I broke...)

> I think it is pbench-agent's job to to create that directory if it need to store the temporary data over there.

Yes, we don't require the user to create our working directories; we cut back on the "hail mary" stuff like using `mkdir -p` everywhere, and we haven't apparently sealed all of the mouse holes yet.

**Comment by portante** [comment]
Digging into this shows that it is a simple solution: create the pbench-agent configuration file specified directory (or our fall back) unconditionally in `agent/base` and `lib/pbench/agent/base.py`.

We need to do this because most of the bench-scripts also do it, but don't ensure it done first all the time, so logging errors files when the `pbench.log` file doesn't exist because the `${pbench_run}` directory doesn't exist.
