### ISSUE TITLE
Mirror pbench data from a remote system

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#277]
We have N- pbench-web-servers installed.  Let's call it a master and N- "satellites".  We would like to mirror the content of the satellites on to the master so that we have a single location to view results.

Options seem to be a pull or push model.  Push requires ssh access to the master, which is not always possible.  A pull model also requires ssh access, but because the population of pbench-web-servers are fairly static, managing a firewall config is tenable.

One suggestion has been that the master would rsync results from all satellites down to it's local storage on a periodic basis.

/cc @ndokos @portante @ekuric

**Comment by jeremyeder** [comment]
@ndokos -- I heard you might be working to add this, any status?

**Comment by ndokos** [comment]
I've got the basics done: rsyncing the remote locally with a prefix to disambiguate controllers and a scheduler to submit jobs to the normal pipeline. The problem is that there are some huge tarballs and I want to make sure that those are done separately (probably manually), so that they don't impact daily usage and don't inflict too much punishment on gluster.. I've run a small example (two hosts and a handful of tarballs) through a simulated run so far and plan to run the same small sample through the whole pipeline, fixing the scheduler as  I go; then run the whole shebang over the weekend. Assuming nothing blows up, that should rsync everything and unpack the vast majority of tarballs, leaving a few to be dealt with by hand later on.

**Comment by jeremyeder** [comment]
Thanks.  What portion of the process deletes results from the remote?

**Comment by ndokos** [comment]
The results are not deleted from the remote by this process. If you want that, I could add it easily enough.

**Comment by jeremyeder** [comment]
I assumed after the tarball transfer there'd be an md5 comparison, and if it matched then it's safe to delete on the remote.  But I don't want to decide this on my own... 

@ekuric @jmencak @mffiedler @portante @timothysc @hroyrh what are your guys thoughts?

**Comment by ndokos** [comment]
I believe the rsync --remove-source-files option does exactly that, but as noted above, it would only get rid of the tarballs, not the unpacked results. We could also redirect results to the internal server and get rid of them on the satellite, but I'd like to leave that for later.

**Comment by ndokos** [comment]
Actually, --remove-source-files would be racy. I'll just add a check-and-delete step at the end of the processing.

**Comment by jeremyeder** [comment]
Right, thanks -- lost results would be bad :-)

**Comment by portante** [comment]
Remaining work on handling remote deletes tracked in #445.
