### ISSUE TITLE
Use a local file system for pbench-server logs

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#311]
Today we use the GlusterFS mount point for pbench server logs.  Instead, we should allow pbench-server logs to land on a local file system.

This work should be coupled with a central logging effort.

**Comment by ndokos** [comment]
I've switched the setting in pbench-base.sh in the production environment so that the logs are under the TOP_LOCAL directory, so if that is defined (and the current crontab jobs always define it to be a local directory), the logs will end up under it.

I also have that change in a branch that I'm going to PR shortly.
