### ISSUE TITLE
Integrate with MPT: Message Performance Tool

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#410]
Let's work on integrating with the [Message Performance Tool, MPT](https://github.com/orpiske/msg-perf-tool).

Here is a possible plan of attack:
1. Write a `pbench-mpt` script which handles the steps described in the MPT README under "Usage - Loader"
   - That script would take all the parameters necessary to drive those steps
2. Write a benchmark post-processing step to:
   - Take the generated CSV files and put them in the pbench result tree
   - Create graphs that load that data from the CSV files (no ES indexing) like the way `pbench-uperf` generates results graphs
3. Take a pbench-result tar ball created with a `pbench-mbt run`, and process it server-side to index/load the CSV files into ES, along with all the other data we are indexing into ES
   - It just means, if I understand how MPT works, that the `mpt-loader.py --load latency ...` and `mpt-loader.py --load throughput ...` calls are made after the fact server-side instead of inline the way the current MPT README describes
   - Once the result tar ball is pulled from the SUT to the central pbench server which handles all the indexing

**Comment by k-rister** [comment]
Seems fairly straight forward.  Once someone generates some CSV files we'll need to look them over and see if they are suitable for our needs with respect to the second part of step 2 above.

I wouldn't be surprised if we have to write a tool to convert their CSV into what we expect in jschart.  If they generate large CSV files (ie. many columns) we will probably want to break it down into smaller files in order to better control what shows up on a single chart.

**Comment by orpiske** [comment]
I have created a first draft of the pbench-mpt script: https://github.com/orpiske/pbench/blob/mpt-integration/agent/bench-scripts/pbench-mpt (here's the output, http://pastebin.com/raw/mUqLjx3K). It's a simplified version of the mpt-runner, without the calls to load the result data into ES. I used pbench-fio as a model for this script.

There's a few things I need to figure out, though. In particular, I need to figure out the best approach for dealing with the installation of mpt, because it's available through COPR. I will reach out on IRC next week to discuss about this.

**Comment by portante** [comment]
@orpiske, great news!  Can you file this as a PR, just marking it as a WIP (work in progress) for now?

@atheurer, perhaps we can get this reviewed next week?

**Comment by orpiske** [comment]
@portante thanks! Absolutely, I will send this as a pull request.

**Comment by ndokos** [comment]
Closed by PR #413 (although @orpiske has promised more patches :-) ).
