### ISSUE TITLE
display units in iostat/disk.html

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#417]
In some of the graphs in iostat/disk.html, there are no units provided, leaving the user to guess.  Sure, you can go read man pages etc but when publishing graphs you want them to be as self-explanatory as possible, so this is important.  Specifically I'd suggest:

- **Request_Merges** changed to **Request_Merges_Per_Sec**
- **Request_Size** changed to **Request_Size_In_512_Byte_Sectors**
- **Throughput** changed to **Throughput_in_MB_per_Sec**
- **Utilization** changed to **Percent_Utilization**
- **Wait_Time** changed to **Wait_Time_in_msec**

Also, is it MB (millions of bytes) or MiB (1024*1024 bytes)? KB or KiB?  In the storage industry this is the [new standard for units](https://en.wikipedia.org/wiki/Units_of_information) imposed to eliminate the ambiguity that was there before, we need to respect that. 

These changes seem cosmetic but they are important when publishing graphs and they become increasingly important as the units increase in size, since a GiB is 7.3% larger than a GB.  

I tried to figure out how to do this myself in **/opt/pbench-agent/tool-scripts/postprocess/iostat-postprocess** script, but the only guess I had was that we had to change all the keys in the perl equivalent of dictionary, for example:

    $iostat{disk}{Utilization}{$dev}{$timestamp_ms} = $util;

Would become:

    $iostat{disk}{percent_Utilization}{$dev}{$timestamp_ms} = $util;

Is that correct?  If so, it's unfortunate that the displayed title of the graph isn't an attribute of the graph, rather than the key in this structure.  For example, you can't use a punctuation mark in the title because of this, correct?

**Comment by ndokos** [comment]
The keys can be quoted "like.th(is)" in order to add punctuation chars e.g. periods, spaces and parens (but some are a no-no, e.g. '/', because the key is also used to create the corresponding CSV file and '/'  cannot be used in filenames). I am submitting a PR and have example output  here: http://pbench.perf.lab.eng.bos.redhat.com/results/alphaville/fio__2016-11-15_22:05:43/1-rw-4KiB/sample4/tools-default/alphaville/iostat/disk.html

BTW, the example output is somewhat fake - both throughput and utilization were below the threshold, so I modified the threshold to be 0 for this example in order to produce the full complement of graphs.

The PR introduces spaces into the keys which also means that the CSV filenames have spaces in them. That should not be a problem in general, but spaces in filenames are a pain to process from the command line, so maybe we don't want to do that: I can change them to underscores if so.

**Comment by bengland2** [comment]
Sample graph looks great. I'm not happy about spaces in filenames.   Are parens ok in filenames?  Parens might confuse scripting etc.  That's why I proposed names with only underscores as separators.   But what matters is that the units are there and easy to read.

**Comment by portante** [comment]
Remaining work tracked in #444.
