### ISSUE TITLE
What are the correct pbench-fio options for each storage types

### ISSUE THREAD

**Issue by schituku** [distributed-system-analysis/pbench#481]
Currently I have my fio options as follows for AWS EBS
pbench-fio --test-types=read,write,rw,randread,randwrite,randrw	--direct=1 --sync=1 --block-sizes=4,64,1024 --iodepth=2 

    My questions are 
1) Are these what one might consider appropriate for EBS?.
2) What are the ideal options one need to set for each type of storage(EBS, Ceph, NFS et al). 
3) Does making direct=1 and sync=1 makes sense?
4) What should be the block-size?
5)The defaults that are currently in place in pbench-fio appropriate for any type of storage?.

**Comment by bengland2** [comment]
no this does not.  I'm going to try to write up a section on how to run pbench-fio in .md format and post it here.

**Comment by jeremyeder** [comment]
A readme for pbench-fio would be awesome :-) Thanks @bengland2 !

**Comment by bengland2** [comment]
[Here's a first draft](https://github.com/bengland2/pbench/blob/bengland2-pbench-fio-doc/agent/bench-scripts/pbench-fio.md), it needs some correction because some of the parameters that are in the job file might be doable from the pbench-fio command line, have to check.  It's urgent we get this done because there are people who need this capability outside our group now.  Feel free to comment on the doc.

**Comment by ndokos** [comment]
This was checked in to pbench master: https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/pbench-fio.md
