### ISSUE TITLE
Speed up loading pidstat?

### ISSUE THREAD

**Issue by hongkailiu** [distributed-system-analysis/pbench#608]
Chrome crashed after several mins.
FireFox did not crash but it did not finish loading after serveral mins.

How do we speed it up?
Something like leaving behind the data below the threadhold?
Or define the threadhold in the url?

Url for replicating the issue.
[non-accessible URL removed]

**Comment by portante** [comment]
@hongkailiu, first could you reposted this example using a public URL?  That URL is internal to Red Hat only, and we should probably not be posted internal URLs to the pubic internet.

Second, can you post the size of the `.csv` file associated with the graph, and using your browser console report how long it took to load the file?

**Comment by k-rister** [comment]
The CSV in question is 30.6MB which is pretty big, my Chrome paused in the debugger to avoid an out-of-memory crash.  At this point the tab process was consuming over 2.2GB (!!) of memory.

I'm going to look into ways to mitigate the issue, but we have to be realistic that there are limits to what we can load into a browser tab.

**Comment by k-rister** [comment]
Problem replicated here:

https://k-rister.github.io/pbench/issues/608/001/cpu_usage.html

**Comment by k-rister** [comment]
It's worth mentioning (to avoid confusion) that jschart is specifically architected to favor run time performance over other considerations such as memory efficiency.  The jschart framework creates all necessary DOM objects upfront and then relies on simple actions like flipping boolean values to change behavior such as whether an object is visible or not.  This minimizes the amount of work that the framework needs to do when actions such as mouse over events and dataset hiding or unhide needs to be performed which greatly improves the user experience.

This approach is only problematic when the amount of data that is being feed to jschart is somewhat over the top.  Typically avoiding things like on the fly DOM node creation really improves the jschart user experience, but in certain situations like this it would probably be more efficient to be doing that.  However, as I said the entire framework is written to optimize run time performance so making a change like that would be very invasive and only beneficial in rare circumstances.

Therefor, I think it's a better idea to develop a work around for this particular problem that is controlled by the user rather than making a framework wide change that would likely degrade the user experience in general.

**Comment by k-rister** [comment]
I now have a more formal prototype but would like some feedback before proceeding any further.  Does this adequately address the issue?

Normal behavior:

https://k-rister.github.io/pbench/issues/608/003/cpu_usage.html

User adjusted behavior:

https://k-rister.github.io/pbench/issues/608/003/cpu_usage.html?threshold=5&threshold_invalidate=true

NOTE:  It is still going to be slow and feel unresponsive, but hopefully this makes it functional.

Let me know what, if any, feedback you have.

**Comment by hongkailiu** [comment]
Sorry that I report late. I will remember to comment without internal urls.
Yes, I can feel the difference between showing the contents of the above 2 URLs.
Is there any way that I can test my origin data?

**Comment by k-rister** [comment]
Here is another prototype:

Normal behavior:

https://k-rister.github.io/pbench/issues/608/004/cpu_usage.html

User adjusted behavior:

https://k-rister.github.io/pbench/issues/608/004/cpu_usage.html?threshold=5&threshold_invalidate_on_load=true

I changed one of the parameters (was threshold_invalidate, now threshold_invalidate_on_load) in an attempt to make it clear that this is only invalidating datasets that fall below the threshold when the page is loaded as opposed to at runtime if the user changes the threshold through the existing page controls.

I also added some documentation and content to the help dialog.  If there are no objects to these implementation changes then I'll be submitting a PR for these changes soon.

**Comment by hongkailiu** [comment]
Cool. My chrome can really feel the difference with and without the parameter.
Thanks.

**Comment by k-rister** [comment]
This code is upstream now.

**Comment by k-rister** [comment]
The code is now deployed and verified.
