### ISSUE TITLE
benchmark postprocessing does not consistently emit the right JSON for server_port field

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#642]
This is related to a perl JSON module behavior change in Fedora 26.

When using Fedora 26 (perl-JSON module version 2.90-8.fc26), the benchmark post-processing unit tests file for uperf-[0:3].

It seems that something has changed in perl to now correctly emit integers as integers instead of strings in .json files.

**Comment by k-rister** [comment]
Not sure if this is relevant, but I had to push this change into a branch owned by @atheurer in order to work around a similar problem: [https://github.com/atheurer/pbench/commit/7021dc1133dfad94c8cdd7564a59b24829388846](https://github.com/atheurer/pbench/commit/7021dc1133dfad94c8cdd7564a59b24829388846)

I used the following test script to validate this:

`
#!/usr/bin/perl                                                                                                                                                                                                                               

use warnings;
use strict;
use JSON;

my %hash;
my @foo;
my $s = 0;
my $r;
my $x = 1;
my $y;


if ($s == 0) {
    $r = 1;
} else {
    $r = 0;
}

if ($x eq 1) {
    $y = 1;
} else {
    $y = 0;
}

push(@foo, { 's' => $s, 'r' => $r, 'x' => $x, 'y' => $y });

$hash{'foo'} = \@foo;

print to_json(\%hash, { ascii => 1, pretty => 1 } );
`

**Comment by portante** [comment]
@atheurer, @ndokos, didn't we resolve this in 0.45 by always emitting string types instead of integers?

**Comment by ndokos** [comment]
Addressed in PR #644.
