### ISSUE TITLE
A question on pbench-fio output

### ISSUE THREAD

**Issue by hongkailiu** [distributed-system-analysis/pbench#735]
I would like to understand how to read the output of pbench-fio output.

Here is an example of the pbench-fio result where it has only one client.
https://imgur.com/a/PLHyy

What is the relationship between mean numbers on server and on client?
The lat on client is 1445.6339 and 725.2616 on server. They seem quite different.

**Comment by hongkailiu** [comment]
pbench version: 0.46-78g30019c5

**Comment by bengland2** [comment]
latency on client is presumably higher because it has to go over the network to ask the server to do work.  Do a ping from client to server and measure mean round-trip time (RTT) from client to server, and see if that accounts for the difference between server and client latency.  pbench measured ~700 usec = 0.7 msec, that sounds a lot like a ping RTT.

**Comment by hongkailiu** [comment]
Hello Ben,

I got very confused.
In the above pic: https://imgur.com/a/PLHyy
client is bigger on client and smaller on server. As you suggested, the cause could be from network.

Can I understand it this way?
In case of only 1 client: lat on client = other latency (like the one caused by network) + lat on the server

However: This is the data from other test: https://imgur.com/a/9sSBR
Note that row 8 (rw-16): lat on client is much smaller than on server. How should we interpret that?

I would be nice to get an example of understanding of pbench-fio output on this page:
https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/pbench-fio.md

It is also interesting to see how pbench-fio converts the numbers generated from fio to the ones on the result.html.

**Comment by bengland2** [comment]
@hongkailiu , yes that's what I'm saying, client latency includes network latency and server latency.  So  how to explain your 2nd test result?   One possibility is that there is client caching, write aggregation, or read prefetch involved, so that there are fewer server I/O requests than client-side I/O requests.

@ndokos  @atheurer I don't understand the column headers here.  There is only 1 client so why have an "all" column in this case, and the "all" column header hints at other hosts involved in the test, but they are not listed in other columns.  Yes, it would be good to explain output in pbench-fio documentation.    But we can't really discuss this using a screenshot, if you could generate a tarball of all the outputs from your pbench-fio run and attach file (it's easy to do), then we could discuss it.

As for numbers generated from fio, you cannot generate cluster-wide latency percentiles from per-thread latency percentiles.  The method to solve this is with latency histogram logs, which pbench-fio does graph.  If you are looking at average latency, it's ok to average the averages.

But it's straightforward to aggregate per-thread throughput metrics to obtain cluster-wide throughput, as long as all threads start and stop at close to the same time.

**Comment by hongkailiu** [comment]
Thanks, Ben.

I sent you an email for the original pbench-data. Hopefully that helps.

**Comment by portante** [comment]
We are not going to try to address this problem at this point in time.  No follow-up occurred beyond the immediate discussion within the week of the report.
