### ISSUE TITLE
page update during navigation

### ISSUE THREAD

**Issue by ashishkamra** [distributed-system-analysis/pbench#841]
When going back and forth between the controllers view, results view or the comparison view, the performance is slow and it seems that the data is being fetched every time we navigate. Can the data be cached to improve performance?

**Comment by gurbirkalsi** [comment]
@ashishkamra I've added caching support for the controller and result view. I'll be implementing a dynamic system for the result and iteration comparison views (perhaps timeouts for data collections) so that the user is seeing new information. Please reference the following commit: https://github.com/distributed-system-analysis/pbench/pull/827/commits/a404ea6b4780e19e34213343b55f5ebb1001bf66

**Comment by gurbirkalsi** [comment]
Closing as this issue has been resolved and merged with PR #951.
