### ISSUE TITLE
Consider merging pbench-backup-tarballs and pbench-verify-backup-tarballs

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#869]
A merge of these two methods would allow us to be sure no bit-rot has occurred before a backup is done without adding additional coordination between the two scripts, or ensure verification of backups is doing immediately following a backup.

**Comment by ndokos** [comment]
Under "normal" circumstances, backup is limited to a small set of tarballs that were submitted recently (since the last time backup ran: currently once an hour - unless the previous run took more than that to finish). OTOH, verify runs over *every* tar ball and so has the potential of running for a very long time (the current setting is once a day I believe). I'm not sure how we could merge the two without major reorg.

**Comment by dbutenhof** [comment]
Won't do.
