### ISSUE TITLE
Pbench-verify-backup-tarballs: $list.p and $list.b variables seems to be empty in comm command

### ISSUE THREAD

**Issue by tenstormavi** [distributed-system-analysis/pbench#900]
The variables $list.p and $list.b used with comm command in pbench-verify-backup-tarballs seems to be empty. These variables were not used in the scripts anywhere before comparing it. I guess these variables should be $out.p, $out.b instead of $list.p and $list.b but not sure need to take a better look.

**Comment by portante** [comment]
@tenstormavi, in bash syntax, isn't `$list.p` is equivalent to `${list}.p`?

**Comment by tenstormavi** [comment]
@portante yes it is.

**Comment by portante** [comment]
So you are saying that `${list}` is empty, but `${out}` is not?

**Comment by tenstormavi** [comment]
@portante No see `list` and `out` are two separate files with process id and it is initialized like:
```
list=$TMP/$PROG/list.$$
out=$TMP/$PROG/out.$$
```

After the initialization `list.p` is never being used within the script except directly in `comm` command that's why the files are empty and there is nothing to compare. But in the case of `out.p`, it is being used to store the md5sum of the results tarball. So Ideally I guess it was meant to compare `out.p` and `out.b` but by mistake some put` list.p` and `list.b` there.

**Comment by portante** [comment]
> No see list and out are two separate files with process id

Right, the initialization is at https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L49.

After initialization then, `${list}.p` will expand to `$TMP/$PROG/list.$$.p`, and `${out}.p` will expand to `$TMP/$PROG/out.$$.p`, right?

But if you search for `${list}` or `$list` where are the references?

 * https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L58
   * we can ignore that in the `trap` call, although there are two references there
 * https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L75
   * On line 75 we see, `$list.$1`, where the first parameter to `checkmd5` is used to construct a file reference, which should expand to `$TMP/$PROG/list.$$.$1`
   * We only create the `$list.$1` files when `allmd5s.$1` has some MD5s in it from https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L69
 * `checkmd5` is called at lines https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L92 and https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L98 with their respective `p` and `b` parameters

So if `${list}.p` is empty, or `${list}.b` is empty, it is likely because https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-verify-backup-tarballs#L69 is never executing.

Can you confirm that in what you are seeing?

**Comment by tenstormavi** [comment]
Yes, you are right Peter. I missed that `$list.$1` and `${list}.p`, `${list}.b` is empty because it was not executing it. Thanks for the detailed clarification.

Closing it because it is not an issue. My understanding was wrong here.
