### ISSUE TITLE
fio with --clients and multiple targets fails

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#908]
For example, pbench-fio --clients=hosta --targets=/tmp/fio1,tmp/fio2

The issue is that --max-jobs is still set to "1"

**Comment by bengland2** [comment]
yeah, when I ran with 3 hosts, --max-jobs=3 used.    Should be --max-jobs=Z where Z is product of number of targets and number of clients (since each client has multiple targets).  Looking at it...  BTW pbench-fio works well with kernel RBD devices (i.e. /dev/rbdX), just haven't got it to work with librbd yet (probably just have to change fio.job to point at different ioengine and supply parameters).

**Comment by bengland2** [comment]
see PR 966

**Comment by portante** [comment]
Fixed by #966.
